[database]
url = "postgresql://postgres.evhkyacjxcughuslwqyw:sup4Gr3sF0rTcc@aws-1-sa-east-1.pooler.supabase.com:6543/postgres"


[storage]
endpoint_url = "https://evhkyacjxcughuslwqyw.storage.supabase.co/storage/v1/s3"
access_key = "b6cbb1fd896a6ab1c74cd10714c9a0fa"
secret_key = "82946f0628f49790f5129a708e30e75da9179908315e98034f738e00cf1b2028"
bucket_name = "smartxl_bucket"


[jwt]
secret_key = "2sTJ4fwYXJYfUuEB82-PLW9tLtXq_WyixN2xx8FaH7g"
